### ISSUE TITLE
Quotes added even without -f flag

### ISSUE THREAD

**Issue by bokub** [ddebin/yaml-sort#25]
Hello !

I tried your tool on following file

```yaml
answers:
  no: Non
  yes: Oui
```

When I run `npx yaml-sort -w -1 -i ./fr.yml`, it's transformed into the following:

```yaml
answers:
  'no': Non
  'yes': Oui
```

Isn't the `forceQuotes` flag supposed to be `false` by default?

How can I prevent the quotes to be automatically added?

Thanks a lot
